# Generated by Django 4.2.6 on 2023-10-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menutreeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='OneLevelMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menutreeapp.menuitem')),
            ],
        ),
    ]
