# Generated by Django 4.2.6 on 2023-10-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menutreeapp', '0002_alter_menuitem_link_onelevelmenuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneLevelMenuItem',
        ),
    ]
